mutation_rate: 0.1
position_mutation_rate: 0.1
connection_mutation_rate: 0.1
function_mutation_rate: 0.1
parameter_mutation_rate: 0.1
output_mutation_rate: 0.1
num_generations: 5000
population_size: 5
num_nodes: 500
fitness_threshold: 0.001
node_inputs: 2
save_best: True
neat_speciation_thresh: 0.02
neat_population: 100
neat_num_generations: 250
neat_init_species: 4
neat_crossover_rate: 0.25
neat_mutation_rate: 0.75
ga_population: 100
ga_num_generations: 250
ga_elitism_rate: 0.1
ga_crossover_rate: 0.25
ga_mutation_rate: 0.65
cmaes_population: 25
cmaes_stopeval: 25000
