# General settings
starting_nodes: 50
static_node_size: 100
node_size_cap: 150
weights: False
mutate_method: ":gene_mutate"
crossover_method: ":proportional_crossover"
recurrency: 0.0
total_evals: 20000
input_start: -1.0
# Logging settings
save_best: False
log_config: False
log_function: ":log_best"
# Mutation
active_mutate: False
input_mutation_rate: 0.0
output_mutation_rate: 0.1
node_mutation_rate: 0.1
node_size_delta: 0.0
modify_mutation_rate: 0.0
# Oneplus settings
lambda: 5
# GA settings
ga_population: 50
ga_elitism_rate: 0.04
ga_crossover_rate: 0.5
ga_mutation_rate: 1.0
