mutation_rate: 0.1
position_mutation_rate: 0.1
connection_mutation_rate: 0.1
function_mutation_rate: 0.1
parameter_mutation_rate: 0.1
output_mutation_rate: 0.1
num_generations: 5000
population_size: 5
num_nodes: 100
fitness_threshold: 0.001
node_inputs: 2
neat_speciation_thresh: 0.02
neat_population: 250
neat_num_generations: 150
neat_init_species: 4
neat_crossover_rate: 0.10
neat_mutation_rate: 0.10
cmaes_population: 25
cmaes_stopeval: 25000
