# General settings
num_nodes: 100
node_size_cap: 1000
node_inputs: 2
save_best: False
mutate_method: ":mixed_node_mutate"
crossover_method: ":output_graph_crossover"
distance_method: ":genetic_distance"
recurrency: 0.0
# Mutation
input_mutation_rate: 0.1
output_mutation_rate: 0.1
node_mutation_rate: 0.1
add_node_rate: 0.1
delete_node_rate: 0.1
add_mutation_rate: 0.25
delete_mutation_rate: 0.15
# Oneplus settings
oneplus_num_generations: 1000
oneplus_population_size: 5
# GA settings
ga_population: 50
ga_num_generations: 100
ga_elitism_rate: 0.1
ga_crossover_rate: 0.25
ga_mutation_rate: 0.65
# Speciation settings
speciation_thresh: 0.8
init_species: 5
# CMAES settings
cmaes_population: 5
cmaes_stopeval: 5000
