language: julia
codecov: true
coveralls: true
julia:
  - 1.3
  - 1.4
  - nightly
os:
  - linux
  # - osx
notifications:
  email: false
stages:
  - deps
  - test
jobs:
  include:
    - stage: "deps"
      julia: 1.0
      os: linux
      script:
        - julia -e 'using Pkg; pkg"add https://github.com/d9w/Cambrian.jl"; Pkg.build(); Pkg.test(coverage=true);'
