language: julia
codecov: true
coveralls: true
julia:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - nightly
os:
  - linux
  # - osx
notifications:
  email: false
install:
  - julia -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true);'
